version: '2'

services:

   plex:
     image: plexinc/pms-docker 
     ports:
        - "32400:32400"
        - "3005:3005"
        - "8324:8324"
        - "32469:32469"
        - "1900:1900"
        - "32410:32410"
        - "32412:32412"
        - "32413:32413"
        - "32414:32414"
     volumes:
        - /etc/nginx/vhost.d
        - /usr/share/nginx/html
        - /certs:/etc/nginx/certs:ro
        - /dockervolumes/plex/database>:/config
        - /dockervolumes/plex/temp>:/transcode
        - /external:/data
     restart: always
     environment:
       ADVERTISE_IP: ${ADVERTISE_IP} 
