version: '2'

services:

   mysql:
     image: mysql:5.7
     volumes:
       - /dockervolumes/owncloud-mysql/db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: owncloud
       MYSQL_USER: owncloud
       MYSQL_PASSWORD: owncloud

   owncloud:
     image: owncloud
     expose:
       - "8080"
     volumes:
       - /dockervolumes/owncloud-app/apps:/var/www/html/apps
       - /dockervolumes/owncloud-app/config:/var/www/html/config
       - /dockervolumes/owncloud-app/data:/var/www/html/data
     restart: always
     environment:
       VIRTUAL_HOST: ${VIRTUAL_HOST}
       LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
