version: '2'

services:

   nginx:
     context: .
     image: jwilder/nginx-proxy
     network: webservices
     ports: 
        - "80:80"
        - "443:443"
     volumes:
        - /etc/nginx/vhost.d
        - /usr/share/nginx/html
        - /certs:/etc/nginx/certs:ro
        - /var/run/docker.sock:/tmp/docker.sock
     labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
     restart: always

   letsencrypt:
     context: .
     image: jrcs/letsencrypt-nginx-proxy-companion
     network: webservices
     volumes:
        - /certs:/etc/nginx/certs
        - /var/run/docker.sock:/var/run/docker.sock:ro
     volumes_from:
        - nginx
