version: '2'

services:
  
 sabnzbd:
    image: "sabnzbd/sabnzbd"
    container_name: "sabnzbd"
    volumes:
        - "/dockervolumes/sabnzbd/datadir:/datadir"
        - "/external:/media"
    ports:
        - "8080:8080"
    restart: always
