version: '2'

services:

   nginx:
     image: jwilder/nginx-proxy
     ports:
        - "80:80"
        - "443:443"
     volumes:
        - /etc/nginx/vhost.d
        - /usr/share/nginx/html
        - /certs:/etc/nginx/certs:ro
        - /var/run/docker.sock:/tmp/docker.sock
     labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
     restart: always

   letsencrypt:
     image: jrcs/letsencrypt-nginx-proxy-companion
     volumes:
        - /certs:/etc/nginx/certs
        - /var/run/docker.sock:/var/run/docker.sock:ro
     volumes_from:
        - nginx
     restart: always

   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress:latest
     expose:
       - "80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       VIRTUAL_HOST: ${VIRTUAL_HOST}
       LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

volumes:
    db_data:
